import Foundation

// مولَّد آلياً — لا يُحرَّر بيد.
// المصدر: KoraTimeAndroid/app/src/main/res/values{,-ar}/strings.xml
// التوليد: python3 KoraTime/Tools/make_localization.py

/// اللغات المدعومة. العربية أولاً لأنها لغة التطبيق الافتراضية.
enum Lang: String, CaseIterable, Identifiable, Codable {
    case ar, en

    var id: String { rawValue }
    var label: String { self == .ar ? "العربية" : "English" }
    var isRTL: Bool { self == .ar }
}

/// جدول النصوص مولَّد من موارد أندرويد نفسها، فلا تفترق ترجمتا
/// التطبيقين. الوسائط بصيغة %1$@ و %1$ld كعادة Foundation.
enum L {

    /// اللغة الحالية تُقرأ مباشرة من التخزين حتى تعمل الدالة في أي سياق.
    static var current: Lang {
        Lang(rawValue: UserDefaults.standard.string(forKey: "general.language") ?? "") ?? .ar
    }

    static func s(_ key: String) -> String {
        let table = current == .ar ? arabic : english
        return table[key] ?? english[key] ?? key
    }

    static func s(_ key: String, _ args: CVarArg...) -> String {
        String(format: s(key), arguments: args)
    }

    private static let arabic: [String: String] = [
        "about": "عن التطبيق",
        "about_desc": "مواعيد المباريات ونتائجها، وقنواتك المفتوحة، وأخبار الكرة العربية في مكان واحد.",
        "about_version": "كورة تايم — الإصدار 1.0",
        "action_add": "إضافة",
        "action_cancel": "إلغاء",
        "action_delete": "حذف",
        "action_save": "حفظ",
        "add_feed": "إضافة خلاصة",
        "add_feed_hint": "الصق رابط RSS لأي موقع رياضي تتابعه.",
        "add_list": "أضف قائمة",
        "add_playlist": "إضافة قائمة قنوات",
        "add_playlist_hint": "رابط قائمة M3U أو ملف JSON فيه قنواتك. القوائم لا تُرفَع لأي خادم — تبقى على جهازك.",
        "all_groups": "كل الفئات",
        "apifootball_hint": "المصدر المجاني المرافق يُرجع ثلاث مباريات يومياً من دوريات هامشية — بلا روشن وبلا الدوريات الكبرى. مفتاح مجاني من dashboard.api-football.com يجلبها كلها. اتركه فارغاً للبقاء على المصدر القديم.",
        "apifootball_key": "مفتاح API-Football (روشن والدوريات الكبرى)",
        "apifootball_placeholder": "الصق المفتاح هنا",
        "app_name": "كورة تايم",
        "arabic_names": "تعريب أسماء الفرق والبطولات",
        "attribution_apifootball": "البيانات من API-Football",
        "attribution_footballdata": "البيانات من football-data.org",
        "attribution_sportsdb": "البيانات من TheSportsDB",
        "auto_refresh_live": "تحديث النتائج المباشرة تلقائياً",
        "autoplay": "تشغيل آخر قناة عند الفتح",
        "cast_device": "جهاز متصل",
        "casting_to": "يُعرض على الشاشة",
        "channel_count": "%1$ld قناة",
        "channel_error": "تعذّر تشغيل هذه القناة. قد تكون محجوبة أو متوقّفة.",
        "channels_footer": "التطبيق لا يوفّر قنوات مشفّرة. أضف روابط بثّك الخاصة أو اشتراكك الرسمي، وستظهر في تبويب القنوات مباشرة.",
        "channels_hint": "التطبيق لا يوفّر قنوات مشفّرة. أضف رابط قائمتك (M3U أو JSON) وستظهر في تبويب القنوات مباشرة. القوائم تبقى على جهازك.",
        "channels_read_failed": "تعذّرت قراءة القنوات المرفقة: %1$@",
        "channels_title": "القنوات",
        "days_ago": "قبل %1$ld يوم",
        "default_channel_name": "قناة",
        "default_group": "قنوات",
        "detail_broadcaster": "الناقل",
        "detail_competition": "البطولة",
        "detail_kickoff": "الموعد",
        "detail_status": "الحالة",
        "detail_venue": "الملعب",
        "edit_prefs": "تعديل الدوريات والفرق",
        "exclusive_competitions": "البطولات الحصرية",
        "extra_time": "وقت إضافي",
        "feed_bbc": "BBC عربي — رياضة",
        "feed_football_agg": "أخبار كرة القدم (تجميع)",
        "feed_invalid_url": "«%1$@»: الرابط غير صالح.",
        "feed_no_items": "«%1$@»: لم تُقرأ أي أخبار من هذه الخلاصة.",
        "feed_sky": "سكاي نيوز عربية — رياضة",
        "feed_transfers": "سوق الانتقالات",
        "feed_url": "رابط خلاصة RSS",
        "feeds_footer": "الخلاصات الافتراضية تجمع أخبار المواقع الرياضية العربية عبر أخبار Google، مع خلاصات مباشرة من مواقع معروفة.",
        "fetch_failed": "تعذّر جلب البيانات",
        "field_name": "الاسم",
        "filter_all": "الكل",
        "filter_live": "المباشرة",
        "footballdata_hint": "يحتاج رمزاً مجانياً من football-data.org. يغطّي الدوريات الأوروبية الكبرى دون الدوري السعودي.",
        "footballdata_key": "مفتاح football-data.org",
        "fullscreen": "ملء الشاشة",
        "group_language": "اللغة",
        "half_first": "الشوط الأول",
        "half_second": "الشوط الثاني",
        "half_time": "الاستراحة",
        "hours_ago": "قبل %1$ld ساعة",
        "http_bad_url": "رابط غير صالح: %1$@",
        "http_decoding": "تعذّرت قراءة بيانات المصدر. %1$@",
        "http_empty": "لا توجد بيانات في هذا المصدر.",
        "http_failed": "تعذّر جلب البيانات (رمز %1$ld).",
        "http_missing_key": "أضف %1$@ من الإعدادات لتفعيل هذا المصدر.",
        "http_no_connection": "تعذّر الاتصال بالمصدر.",
        "http_not_found": "المصدر غير موجود (404).",
        "http_rate_limited": "تجاوزت حدّ الطلبات المسموح به. انتظر قليلاً.",
        "http_rejected": "المصدر رفض الطلب (%1$ld). تأكّد من المفتاح في الإعدادات.",
        "http_server_down": "خادم المصدر لا يستجيب حالياً (%1$ld).",
        "in_days_hours": "بعد %1$ld ي %2$ld س",
        "in_hours_minutes": "بعد %1$ld س %2$ld د",
        "in_minutes": "بعد %1$ld د",
        "just_now": "الآن",
        "language_hint": "التطبيق يفتح بالعربية. تغيير اللغة يعيد بناء الشاشة.",
        "last_updated": "آخر تحديث %1$@",
        "loading": "جارٍ التحميل…",
        "loading_matches_day": "جارٍ جلب مباريات %1$@…",
        "loading_news": "جارٍ جلب الأخبار…",
        "manage_feeds": "إدارة الخلاصات",
        "match_news": "أخبار المباراة",
        "matches_error": "تعذّر جلب المباريات",
        "matches_fetch_failed": "تعذّر جلب المباريات.",
        "matches_live_now": "%1$ld مباراة جارية الآن",
        "matches_source": "مصدر المباريات",
        "matches_title": "المباريات",
        "may_be_blocked": "قد تُحجب",
        "minimize": "تصغير",
        "minutes_ago": "قبل %1$ld دقيقة",
        "monogram_unknown": "؟",
        "my_channels": "قنواتي",
        "my_feed": "خلاصة مخصّصة",
        "my_list": "قائمتي",
        "my_prefs": "تفضيلاتي",
        "my_prefs_hint": "الدوريات والفرق التي اخترتها ترتّب جدول المباريات وتبني خلاصات الأخبار.",
        "news_feed_error": "«%1$@»: %2$@",
        "news_from_feeds": "من الخلاصات التي تتابعها",
        "news_my_feeds": "متابعاتي",
        "news_no_feeds": "لم تُفعّل أي خلاصة أخبار.",
        "news_no_feeds_add": "لم تُفعّل أي خلاصة أخبار. أضف واحدة من الإعدادات.",
        "news_none": "لا توجد أخبار",
        "news_search_feed": "نتائج %1$@",
        "news_search_results": "نتائج البحث عن «%1$@»",
        "news_title": "الأخبار",
        "news_try_other": "جرّب موضوعاً آخر.",
        "news_try_other_or_add": "جرّب موضوعاً آخر أو أضف خلاصة من الإعدادات.",
        "next": "التالي",
        "no_channels": "لا قنوات",
        "no_feeds": "لا خلاصات مضافة",
        "no_live_matches": "لا توجد مباريات جارية",
        "no_matches_day": "لا مباريات في هذا اليوم",
        "no_playlists": "لا قوائم مضافة",
        "numbered_channel": "قناة %1$ld",
        "onb_leagues_sub": "نرتّب لك جدول المباريات ونجمع أخبارها.",
        "onb_leagues_title": "أي الدوريات تتابع؟",
        "onb_no_teams": "الدوريات التي اخترتها بلا قائمة فرق هنا. تقدر تكمل.",
        "onb_teams_sub": "تظهر أخبار فرقك أولاً، ومبارياتها في صدر الجدول.",
        "onb_teams_title": "أي الفرق تشجّع؟",
        "open_broadcaster": "فتح %1$@",
        "open_channels": "القنوات المفتوحة",
        "open_settings_key": "فتح الإعدادات لإضافة المفتاح",
        "other_competitions": "بطولات أخرى",
        "penalties": "ركلات الترجيح",
        "pick_another_day": "اختر يوماً آخر من الشريط أعلاه.",
        "pick_channel": "اختر قناة من القائمة",
        "playlist_error": "«%1$@»: %2$@",
        "playlist_no_channels": "«%1$@»: لم يُعثر على قنوات.",
        "playlist_url": "رابط قائمة قنوات",
        "rail_below": "تحت المشغّل",
        "rail_placement": "مكان قائمة القنوات",
        "rail_side": "على الجانب",
        "refresh": "تحديث",
        "restore_feeds": "استعادة الخلاصات الافتراضية",
        "retry": "إعادة المحاولة",
        "round_no": "الجولة %1$@",
        "score_separator": "—",
        "search_hint_matches": "ابحث عن فريق أو بطولة",
        "search_hint_news": "ابحث عن فريق أو خبر",
        "section_live_count": "%1$ld مباشر",
        "send_to_app": "إرسال إلى تطبيق آخر",
        "settings_display": "العرض",
        "settings_news_rss": "خلاصات RSS",
        "settings_subtitle": "مصادر البيانات، قنواتك، وخلاصات الأخبار",
        "settings_title": "الإعدادات",
        "settings_version": "الإصدار",
        "show_all": "عرض الكل",
        "show_demo": "إظهار القنوات التجريبية",
        "signup_key": "كيف أحصل على مفتاح مجاني؟",
        "skip": "تخطّي",
        "sportsdb_hint": "المفتاح التجريبي المشترك «123» يعمل بلا تسجيل لكنه محدود الطلبات. سجّل مفتاحاً باسمك من thesportsdb.com لتحديث أسرع.",
        "sportsdb_key": "مفتاح TheSportsDB",
        "start": "ابدأ",
        "starts_in": "تبدأ %1$@",
        "status_canceled": "ملغاة",
        "status_finished": "انتهت",
        "status_in_play": "جارية",
        "status_live": "مباشر",
        "status_postponed": "مؤجلة",
        "status_scheduled": "لم تبدأ",
        "tab_channels": "القنوات",
        "tab_matches": "المباريات",
        "tab_news": "الأخبار",
        "tab_settings": "الإعدادات",
        "today": "اليوم",
        "tomorrow": "غداً",
        "topic_football": "كرة القدم",
        "topic_ksa_team": "المنتخب السعودي",
        "topic_transfers": "انتقالات",
        "try_all_hint": "جرّب «الكل» لعرض مباريات اليوم كاملة.",
        "unknown_model": "نموذج غير معروف: %1$@",
        "update_available": "يتوفّر تحديث لكورة تايم",
        "update_later": "لاحقاً",
        "update_now": "تحديث",
        "update_required_body": "صدر تحديث ضروري لكورة تايم. حدّث لتواصل الاستخدام.",
        "update_required_title": "هذا الإصدار لم يعد يعمل",
        "update_version": "الإصدار %1$@",
        "watch_on": "شاهد على %1$@",
        "yesterday": "أمس",
        "your_channels": "قنواتك الخاصة",
        "your_channels_hint": "أضف رابط قائمتك (M3U أو JSON) من الإعدادات وستظهر هنا.",
    ]

    private static let english: [String: String] = [
        "about": "About",
        "about_desc": "Fixtures and results, your open channels, and Arab football news in one place.",
        "about_version": "Kora Time — version 1.0",
        "action_add": "Add",
        "action_cancel": "Cancel",
        "action_delete": "Delete",
        "action_save": "Save",
        "add_feed": "Add a feed",
        "add_feed_hint": "Paste the RSS link of any sports site you follow.",
        "add_list": "Add a list",
        "add_playlist": "Add a channel list",
        "add_playlist_hint": "An M3U playlist or a JSON file with your channels. Lists are never uploaded — they stay on your device.",
        "all_groups": "All categories",
        "apifootball_hint": "The bundled free source returns only 3 matches a day from minor leagues — no Roshn and no major leagues. A free key from dashboard.api-football.com brings them all. Leave it empty to stay on the old source.",
        "apifootball_key": "API-Football key (Roshn + major leagues)",
        "apifootball_placeholder": "Paste your key here",
        "app_name": "Kora Time",
        "arabic_names": "Arabic team and league names",
        "attribution_apifootball": "Data from API-Football",
        "attribution_footballdata": "Data from football-data.org",
        "attribution_sportsdb": "Data from TheSportsDB",
        "auto_refresh_live": "Refresh live scores automatically",
        "autoplay": "Resume the last channel on open",
        "cast_device": "Connected device",
        "casting_to": "Playing on your screen",
        "channel_count": "%1$ld channels",
        "channel_error": "This channel would not play. It may be blocked or off air.",
        "channels_footer": "The app carries no encrypted channels. Add your own stream links or official subscription and they appear in the Channels tab.",
        "channels_hint": "The app carries no encrypted channels. Add your own list (M3U or JSON) and it appears in the Channels tab. Lists stay on your device.",
        "channels_read_failed": "Could not read the bundled channels: %1$@",
        "channels_title": "Channels",
        "days_ago": "%1$ld d ago",
        "default_channel_name": "Channel",
        "default_group": "Channels",
        "detail_broadcaster": "Broadcaster",
        "detail_competition": "Competition",
        "detail_kickoff": "Kick-off",
        "detail_status": "Status",
        "detail_venue": "Venue",
        "edit_prefs": "Edit leagues and teams",
        "exclusive_competitions": "Exclusive competitions",
        "extra_time": "Extra time",
        "feed_bbc": "BBC Arabic — Sport",
        "feed_football_agg": "Football news (aggregated)",
        "feed_invalid_url": "“%1$@”: invalid URL.",
        "feed_no_items": "“%1$@”: no news read from this feed.",
        "feed_sky": "Sky News Arabia — Sport",
        "feed_transfers": "Transfer market",
        "feed_url": "RSS feed URL",
        "feeds_footer": "The default feeds gather Arabic sports coverage through Google News, plus direct feeds from known sites.",
        "fetch_failed": "Could not fetch data",
        "field_name": "Name",
        "filter_all": "All",
        "filter_live": "Live",
        "footballdata_hint": "Needs a free token from football-data.org. Covers the major European leagues but not the Saudi league.",
        "footballdata_key": "football-data.org key",
        "fullscreen": "Full screen",
        "group_language": "Language",
        "half_first": "1st half",
        "half_second": "2nd half",
        "half_time": "Half time",
        "hours_ago": "%1$ld h ago",
        "http_bad_url": "Invalid URL: %1$@",
        "http_decoding": "Could not read the source data. %1$@",
        "http_empty": "No data from this source.",
        "http_failed": "Could not fetch data (code %1$ld).",
        "http_missing_key": "Add %1$@ in Settings to enable this source.",
        "http_no_connection": "Could not reach the source.",
        "http_not_found": "Source not found (404).",
        "http_rate_limited": "You have hit the request limit. Wait a moment.",
        "http_rejected": "The source refused the request (%1$ld). Check the key in Settings.",
        "http_server_down": "The source server is not responding (%1$ld).",
        "in_days_hours": "in %1$ldd %2$ldh",
        "in_hours_minutes": "in %1$ldh %2$ldm",
        "in_minutes": "in %1$ldm",
        "just_now": "Now",
        "language_hint": "The app opens in Arabic. Changing the language restarts the screen.",
        "last_updated": "Updated %1$@",
        "loading": "Loading…",
        "loading_matches_day": "Loading %1$@ fixtures…",
        "loading_news": "Loading news…",
        "manage_feeds": "Manage feeds",
        "match_news": "Match news",
        "matches_error": "Could not load matches",
        "matches_fetch_failed": "Could not load matches.",
        "matches_live_now": "%1$ld match(es) live now",
        "matches_source": "Matches source",
        "matches_title": "Matches",
        "may_be_blocked": "May be blocked",
        "minimize": "Exit full screen",
        "minutes_ago": "%1$ld min ago",
        "monogram_unknown": "?",
        "my_channels": "My channels",
        "my_feed": "Custom feed",
        "my_list": "My list",
        "my_prefs": "My preferences",
        "my_prefs_hint": "The leagues and teams you pick order the fixtures and build your news feeds.",
        "news_feed_error": "“%1$@”: %2$@",
        "news_from_feeds": "From the feeds you follow",
        "news_my_feeds": "My feeds",
        "news_no_feeds": "No news feed is enabled.",
        "news_no_feeds_add": "No news feed is enabled. Add one in Settings.",
        "news_none": "No news",
        "news_search_feed": "Results for %1$@",
        "news_search_results": "Results for “%1$@”",
        "news_title": "News",
        "news_try_other": "Try another topic.",
        "news_try_other_or_add": "Try another topic or add a feed in Settings.",
        "next": "Next",
        "no_channels": "No channels",
        "no_feeds": "No feeds added",
        "no_live_matches": "No live matches",
        "no_matches_day": "No matches on this day",
        "no_playlists": "No lists added",
        "numbered_channel": "Channel %1$ld",
        "onb_leagues_sub": "We will order your fixtures and gather their news.",
        "onb_leagues_title": "Which leagues do you follow?",
        "onb_no_teams": "The leagues you picked have no team list here. You can continue.",
        "onb_teams_sub": "Your teams' news comes first, and their matches head the table.",
        "onb_teams_title": "Which teams do you support?",
        "open_broadcaster": "Open %1$@",
        "open_channels": "Free-to-air channels",
        "open_settings_key": "Open Settings to add the key",
        "other_competitions": "Other competitions",
        "penalties": "Penalties",
        "pick_another_day": "Pick another day from the strip above.",
        "pick_channel": "Pick a channel from the list",
        "playlist_error": "“%1$@”: %2$@",
        "playlist_no_channels": "“%1$@”: no channels found.",
        "playlist_url": "Channel list URL",
        "rail_below": "Below the player",
        "rail_placement": "Channel list position",
        "rail_side": "Beside the player",
        "refresh": "Refresh",
        "restore_feeds": "Restore the default feeds",
        "retry": "Try again",
        "round_no": "Round %1$@",
        "score_separator": "—",
        "search_hint_matches": "Search for a team or competition",
        "search_hint_news": "Search for a team or story",
        "section_live_count": "%1$ld live",
        "send_to_app": "Send to another app",
        "settings_display": "Display",
        "settings_news_rss": "RSS feeds",
        "settings_subtitle": "Data sources, your channels, and news feeds",
        "settings_title": "Settings",
        "settings_version": "Version",
        "show_all": "Show all",
        "show_demo": "Show demo channels",
        "signup_key": "How do I get a free key?",
        "skip": "Skip",
        "sportsdb_hint": "The shared trial key “123” works without signing up but is rate limited. Register your own at thesportsdb.com for faster updates.",
        "sportsdb_key": "TheSportsDB key",
        "start": "Start",
        "starts_in": "Starts %1$@",
        "status_canceled": "Cancelled",
        "status_finished": "Ended",
        "status_in_play": "In play",
        "status_live": "Live",
        "status_postponed": "Postponed",
        "status_scheduled": "Not started",
        "tab_channels": "Channels",
        "tab_matches": "Matches",
        "tab_news": "News",
        "tab_settings": "Settings",
        "today": "Today",
        "tomorrow": "Tomorrow",
        "topic_football": "Football",
        "topic_ksa_team": "Saudi national team",
        "topic_transfers": "Transfers",
        "try_all_hint": "Tap “All” to see the full day.",
        "unknown_model": "Unknown view model: %1$@",
        "update_available": "A Kora Time update is available",
        "update_later": "Later",
        "update_now": "Update",
        "update_required_body": "A required Kora Time update is out. Update to keep going.",
        "update_required_title": "This version no longer works",
        "update_version": "Version %1$@",
        "watch_on": "Watch on %1$@",
        "yesterday": "Yesterday",
        "your_channels": "Your own channels",
        "your_channels_hint": "Add your playlist URL (M3U or JSON) in Settings and it will show up here.",
    ]
}
